"""
engine.py  —  The biochar supply-chain model, explained line by line.
===========================================================================

WHAT THIS FILE IS
-----------------
This is the "engine": the part that actually does the thinking. It takes a set
of wood-chip producers (each one a point on the map that offers some biomass),
and it decides WHERE to build biochar plants and HOW to send each producer's
chips to a plant, so that the whole chain is as cheap as possible. Then it works
out the price of a carbon credit that would let the chain just break even.

It is organised in the same order as the thesis:

  1. DISTANCES      how far every producer is from every candidate site.
  2. PARAMETERS     all the economic and environmental numbers in one place.
  3. SCALE BLOCKS   the two ways of pricing a plant (big one with economies of
                    scale, or many small identical modules).
  4. STAGE A        the optimisation: where to build and how to route the chips.
  5. STAGE B        the money-and-carbon balance -> the break-even carbon credit.
  6. REFERENCE LAYOUTS  deliberately non-optimal plans, used only for comparison.

You normally do NOT edit this file. The numbers you may want to play with live
in `toy_data.py`. This file just uses them.
"""

# "from __future__" makes newer type-hint syntax work on older Python too; it is
# a harmless compatibility line that must sit at the very top of the file.
from __future__ import annotations

# `dataclass` lets us make a small "record" object (a tidy bag of named fields)
# without writing boilerplate; we use it for the scale blocks and the solution.
from dataclasses import dataclass
# `ceil` rounds a number UP to the next whole number; we need it to count whole
# plant modules (you cannot build half a module).
from math import ceil

# numpy is the library for fast arrays and maths (used for the distance matrix).
import numpy as np
# pyomo is the library that lets us WRITE an optimisation problem in Python and
# hand it to a solver; "pyo" is just a short nickname for it.
import pyomo.environ as pyo

# The name of the solver that actually crunches the optimisation. HiGHS is a
# free, well-known solver for this family of problems (mixed-integer linear).
SOLVER = "appsi_highs"


# =============================================================================
# 1. DISTANCES
# =============================================================================
def distance_matrix_km(lats, lons) -> np.ndarray:
    """Return a table of straight-line distances (in km) between every pair of
    points, given their latitudes and longitudes.

    The Earth is a sphere, so we cannot just subtract coordinates; we use the
    "haversine" formula, which gives the great-circle distance (the shortest
    distance over the surface of a sphere). The result is a square table where
    entry [a, b] is the distance from point a to point b.
    """
    # The radius of the Earth in kilometres: the scale factor of the formula.
    R = 6371.0
    # Convert the latitudes from degrees to radians, because trigonometry
    # functions in maths libraries expect radians, not degrees.
    la = np.radians(np.asarray(lats, float))
    # Same conversion for the longitudes.
    lo = np.radians(np.asarray(lons, float))
    # Difference in latitude between every pair of points (a grid of differences).
    dla = la[:, None] - la[None, :]
    # Difference in longitude between every pair of points (same idea).
    dlo = lo[:, None] - lo[None, :]
    # The core of the haversine formula: it combines the two differences with the
    # latitudes to get a number between 0 and 1 for each pair of points.
    a = np.sin(dla / 2) ** 2 + np.cos(la)[:, None] * np.cos(la)[None, :] * np.sin(dlo / 2) ** 2
    # Turn that number into an actual distance in km and hand the whole table back.
    return 2 * R * np.arcsin(np.sqrt(a))


# =============================================================================
# 2. PARAMETERS
# =============================================================================
def capital_recovery_factor(rate: float, life_years: int) -> float:
    """Turn a one-off investment into an equal yearly payment.

    If you spend a big sum once to build a plant, this factor tells you the
    constant amount you would have to set aside every year, for `life_years`
    years, at interest `rate`, to pay that sum back. It is the standard way to
    compare a one-time building cost with yearly running costs on equal footing.
    """
    # The classic capital-recovery-factor formula from engineering economics.
    return rate * (1 + rate) ** life_years / ((1 + rate) ** life_years - 1)


# =============================================================================
# 3. SCALE BLOCKS  —  the two ways of pricing a plant
#    A "scale block" knows ONE thing: how much a plant costs per year, and how
#    big it is. Everything else in the model is the same for both; swapping the
#    block is how we switch between the two scenarios.
# =============================================================================
@dataclass
class ConcaveScalePWL:
    """THEORETICAL plant with economies of scale (the "0.6 power" rule).

    A bigger plant costs more, but LESS than proportionally: doubling the size
    multiplies the cost by only about 2**0.6 ~ 1.5. That curve is the reward for
    concentrating production. A solver cannot handle a curve directly (it only
    speaks in straight lines), so we approximate the curve with a chain of short
    straight segments — a "piecewise-linear" (PWL) approximation.
    """
    # A human-readable name for this block, used in printouts and figure titles.
    name: str = "theoretical"
    # The capital cost of a reference plant of size `y_ref` (euros, one-off).
    capex_ref: float = 26.6e6
    # The reference plant size, in tonnes of chips per hour.
    y_ref: float = 5.0
    # The scale exponent: 0.6 is the engineers' rule of thumb for this cost curve.
    R: float = 0.6
    # Yearly running cost, written as a fraction of the one-off building cost.
    opex_frac: float = 0.02
    # The smallest plant size the curve is sampled from (tonnes/hour).
    y_min: float = 0.5
    # The largest plant size allowed; this is one of the knobs worth varying.
    y_max: float = 30.0
    # How many straight segments approximate the curve: more = smoother but slower.
    n_seg: int = 15

    def _yearly_factor(self, p):
        """The part of the cost that does NOT depend on plant size.

        It bundles the yearly capital payment and the running cost together, so
        that the size-dependent part is just a clean power of the size.
        """
        # (yearly-capital-payment-rate + running-cost-fraction) times the reference cost.
        return (capital_recovery_factor(p["rate"], p["life_years"]) + self.opex_frac) * self.capex_ref

    def direct_yearly_cost(self, y_t_h, p):
        """The TRUE curve cost (not the straight-line approximation) of a plant
        of size `y_t_h`. Used only for the hand-made reference layouts."""
        # Cost = fixed factor * (size / reference size) raised to the 0.6 power.
        return self._yearly_factor(p) * (max(y_t_h, 1e-9) / self.y_ref) ** self.R

    def add_to_model(self, m, p):
        """Add to the optimisation model `m` the plant SIZE, the plant COST, and
        the straight-line approximation of the cost curve.

        The trick: we pick a handful of sample sizes along the curve, and we let
        the solver describe each plant's size and cost as a weighted blend of two
        neighbouring samples. Binary switches force the blend to use only ONE
        segment at a time, so the blend stays ON the curve instead of cutting
        corners across it.
        """
        # The sample sizes: evenly spaced points from the smallest to the largest size.
        yp = np.linspace(self.y_min, self.y_max, self.n_seg + 1)
        # The TRUE cost at each of those sample sizes (points sitting on the curve).
        cp = self._yearly_factor(p) * (yp / self.y_ref) ** self.R
        # The list of sample points (their position numbers 0,1,2,...).
        KP = list(range(len(yp)))
        # The list of segments between consecutive points (one fewer than the points).
        SG = list(range(self.n_seg))
        # The plant size variable for each candidate site, between 0 and y_max.
        m.y = pyo.Var(m.J, domain=pyo.NonNegativeReals, bounds=(0, self.y_max))
        # Register the point and segment lists with the model so constraints can use them.
        m.KP = pyo.Set(initialize=KP)
        m.SG = pyo.Set(initialize=SG)
        # The blending weights: how much each sample point counts for each site.
        m.lam = pyo.Var(m.J, m.KP, domain=pyo.NonNegativeReals)
        # The on/off switch for each segment at each site (1 if that segment is the active one).
        m.b = pyo.Var(m.J, m.SG, domain=pyo.Binary)
        # The yearly fixed cost of each site (filled in by the blend below).
        m.C = pyo.Var(m.J, domain=pyo.NonNegativeReals)
        # Effective operating hours per year, needed to turn a yearly tonnage into a per-hour size.
        hours = p["hours_per_year"]
        # Capacity rule: the chips sent to site j must fit within what a plant of size y[j] can process in a year.
        m.cap_flow = pyo.Constraint(
            m.J, rule=lambda m, j: sum(m.z[i, j] * m.S[i] for i in m.I) <= m.y[j] * hours)
        # Define the size as the weighted blend of the sample sizes.
        m.pw_def_y = pyo.Constraint(m.J, rule=lambda m, j: m.y[j] == sum(m.lam[j, k] * yp[k] for k in m.KP))
        # Define the cost as the SAME weighted blend of the sample costs (so cost follows size along the curve).
        m.pw_def_C = pyo.Constraint(m.J, rule=lambda m, j: m.C[j] == sum(m.lam[j, k] * cp[k] for k in m.KP))
        # The weights add up to x[j]: they sum to 1 if the plant is open, and to 0 if it is closed.
        m.pw_sum = pyo.Constraint(m.J, rule=lambda m, j: sum(m.lam[j, k] for k in m.KP) == m.x[j])
        # Exactly one segment is active when the plant is open, none when it is closed.
        m.pw_oneseg = pyo.Constraint(m.J, rule=lambda m, j: sum(m.b[j, s] for s in m.SG) == m.x[j])

        def adjacency(m, j, k):
            # A sample point may carry weight only if it is an endpoint of the active segment.
            if k == 0:
                # The first point belongs to the first segment only.
                return m.lam[j, 0] <= m.b[j, 0]
            if k == KP[-1]:
                # The last point belongs to the last segment only.
                return m.lam[j, k] <= m.b[j, k - 1]
            # An inner point belongs to the two segments it sits between.
            return m.lam[j, k] <= m.b[j, k - 1] + m.b[j, k]
        # Apply that adjacency rule to every point of every site.
        m.pw_adj = pyo.Constraint(m.J, m.KP, rule=adjacency)

    def solution_capacity(self, m, j):
        """Read back the chosen plant size (tonnes/hour) for site j after solving."""
        # The solver stored the size in m.y[j]; we just read its value.
        return pyo.value(m.y[j])


@dataclass
class LinearModulesScale:
    """REALISTIC plant made of identical small modules (no economies of scale).

    Here a plant is simply a stack of identical Biodea-style modules. Each module
    has a fixed cost and a fixed throughput, so the cost grows in a straight line
    with the number of modules: building twice as much costs exactly twice as
    much. There is no reward for getting bigger.
    """
    # A human-readable name for this block.
    name: str = "realistic"
    # The one-off capital cost of a single module (euros).
    capex_mod: float = 1.6e6
    # How much dry biomass one module can process in a year (tonnes).
    cap_mod_t_year: float = 401.5
    # Yearly running cost of a module, as a fraction of its building cost.
    opex_frac: float = 0.028
    # A generous upper limit on modules per site (high enough to never bind).
    n_max_mod: int = 400

    def module_yearly_cost(self, p):
        """The yearly cost of one module (its capital payment plus running cost)."""
        # (yearly-capital-payment-rate + running-cost-fraction) times the module cost.
        return (capital_recovery_factor(p["rate"], p["life_years"]) + self.opex_frac) * self.capex_mod

    @property
    def y_mod_t_h(self):
        """A module's throughput expressed per hour (only used to report sizes)."""
        # Yearly throughput spread over a year of operating hours (90% of 8760 hours).
        return self.cap_mod_t_year / (0.90 * 8760)

    def direct_yearly_cost(self, y_t_h, p):
        """Cost of enough whole modules to cover a required size `y_t_h`."""
        # Turn the per-hour requirement into a yearly tonnage the modules must cover.
        hours = p["hours_per_year"]
        # How much one module covers per hour.
        cap_mod_th = self.cap_mod_t_year / hours
        # Round UP to a whole number of modules (you cannot build a fraction of one).
        n = ceil(max(y_t_h, 1e-9) / cap_mod_th)
        # The total cost is simply that many modules times the cost of one.
        return n * self.module_yearly_cost(p)

    def add_to_model(self, m, p):
        """Add to the model the NUMBER of modules per site, the (linear) cost, and
        the capacity and on/off linking rules."""
        # The yearly cost of a single module (computed once).
        cm = self.module_yearly_cost(p)
        # The throughput of a single module (computed once).
        capmod = self.cap_mod_t_year
        # The number of modules at each site: a whole number between 0 and the cap.
        m.n = pyo.Var(m.J, domain=pyo.NonNegativeIntegers, bounds=(0, self.n_max_mod))
        # The yearly fixed cost of each site (filled in by the linear rule below).
        m.C = pyo.Var(m.J, domain=pyo.NonNegativeReals)
        # Capacity rule: chips sent to site j must fit within what its modules can process.
        m.cap_flow = pyo.Constraint(
            m.J, rule=lambda m, j: sum(m.z[i, j] * m.S[i] for i in m.I) <= m.n[j] * capmod)
        # If the site is closed (x=0) it can have no modules; the cap only applies when open.
        m.link_up = pyo.Constraint(m.J, rule=lambda m, j: m.n[j] <= self.n_max_mod * m.x[j])
        # If the site is open (x=1) it must have at least one module.
        m.link_lo = pyo.Constraint(m.J, rule=lambda m, j: m.n[j] >= m.x[j])
        # The fixed cost is the number of modules times the cost of one module (a straight line).
        m.def_C = pyo.Constraint(m.J, rule=lambda m, j: m.C[j] == cm * m.n[j])

    def solution_capacity(self, m, j):
        """Read back the chosen size as number-of-modules times a module's size."""
        # Modules chosen by the solver, converted back to a per-hour size.
        return pyo.value(m.n[j]) * self.y_mod_t_h


# =============================================================================
# 4. STAGE A  —  the optimisation (where to build, how to route)
# =============================================================================
@dataclass
class StageASolution:
    """A tidy bag holding everything the optimiser decided, ready for Stage B."""
    ids: list          # the list of node names.
    S: dict            # node -> dry biomass (tonnes/year).
    dist: np.ndarray   # the full distance table (km).
    idx: dict          # node -> its position number in the distance table.
    x: dict            # site -> 1 if a plant is open there, else 0.
    z: dict            # (producer, site) -> fraction of that producer's chips sent there.
    cap_th: dict       # site -> chosen plant size (tonnes/hour).
    C: dict            # site -> yearly fixed cost (euros).
    proc: dict         # site -> biomass actually processed there (tonnes/year).
    fixed_cost: float  # total yearly fixed cost across all open plants.
    transport_cost: float  # total yearly transport cost.
    tonne_km: float    # total tonne-kilometres (used for cost and for emissions).
    status: str        # the solver's report (e.g. "optimal").


def solve_stage_A(nodes, p, scale, transport_cost_tkm) -> StageASolution:
    """Build and solve the location problem: decide which plants to open and how
    to route every producer's chips, so that fixed cost plus transport cost is as
    small as possible.

    `nodes` is the table of producers, `p` the parameters, `scale` one of the two
    scale blocks above, and `transport_cost_tkm` the price of moving one tonne one
    kilometre (one of the knobs worth varying).
    """
    # The list of node names, in order (both producers and candidate sites use it).
    ids = nodes["node"].tolist()
    # A lookup from node name to its dry biomass (tonnes/year).
    S = dict(zip(nodes["node"], nodes["S"]))
    # The latitudes and longitudes as number arrays, to build the distance table.
    lat = nodes["lat"].to_numpy()
    lon = nodes["lon"].to_numpy()
    # The full table of distances between every pair of nodes.
    dist = distance_matrix_km(lat, lon)
    # A lookup from node name to its row/column number in that table.
    idx = {i: k for k, i in enumerate(ids)}
    # The transport COST between every pair = distance times the per-tonne-km price.
    T = {(ids[a], ids[b]): float(dist[a, b]) * transport_cost_tkm
         for a in range(len(ids)) for b in range(len(ids))}

    # Create an empty optimisation model to fill in.
    m = pyo.ConcreteModel()
    # The set of producer nodes (the supply points).
    m.I = pyo.Set(initialize=ids)
    # The set of candidate sites (here identical to the producers: every producer could host a plant).
    m.J = pyo.Set(initialize=ids)
    # The dry biomass available at each producer, as a model input.
    m.S = pyo.Param(m.I, initialize=S)
    # The transport cost for each producer-site pair, as a model input.
    m.T = pyo.Param(m.I, m.J, initialize=T)
    # The decision "open a plant at site j?" — 1 for yes, 0 for no.
    m.x = pyo.Var(m.J, domain=pyo.Binary)
    # The decision "what fraction of producer i's chips go to site j?" — between 0 and 1.
    m.z = pyo.Var(m.I, m.J, domain=pyo.NonNegativeReals, bounds=(0, 1))
    # Rule: all of each producer's chips must be sent somewhere (the fractions add up to 1).
    m.allocate = pyo.Constraint(m.I, rule=lambda m, i: sum(m.z[i, j] for j in m.J) == 1)
    # Rule: chips may only be sent to a site that is actually open.
    m.linking = pyo.Constraint(m.I, m.J, rule=lambda m, i, j: m.z[i, j] <= m.x[j])
    # Hand the model over to the chosen scale block, which adds the size, cost and capacity rules.
    scale.add_to_model(m, p)
    # The goal: minimise the total yearly fixed cost of the plants plus the total transport cost.
    m.obj = pyo.Objective(sense=pyo.minimize,
                          rule=lambda m: sum(m.C[j] for j in m.J)
                          + sum(m.T[i, j] * m.S[i] * m.z[i, j] for i in m.I for j in m.J))
    # Run the solver on the model (this is the actual number-crunching step).
    res = pyo.SolverFactory(SOLVER).solve(m)
    # Record how the solver finished (ideally "optimal").
    status = str(getattr(getattr(res, "solver", None), "termination_condition", "n/a"))

    # Read the open/closed decision for each site back into a plain dictionary.
    xval = {j: pyo.value(m.x[j]) for j in ids}
    # Read the routing fractions back into a plain dictionary.
    zval = {(i, j): pyo.value(m.z[i, j]) for i in ids for j in ids}
    # Read the chosen plant size for every OPEN site (0 for closed sites).
    cap = {j: (scale.solution_capacity(m, j) if xval[j] > 0.5 else 0.0) for j in ids}
    # Read the yearly fixed cost of every site.
    Cval = {j: pyo.value(m.C[j]) for j in ids}
    # Work out how much biomass each site actually ends up processing.
    proc = {j: sum(zval[i, j] * S[i] for i in ids) for j in ids}
    # Add up the fixed cost over all sites.
    fixed_cost = sum(Cval.values())
    # Add up the transport cost over all producer-site pairs.
    transport_cost = sum(zval[i, j] * S[i] * T[i, j] for i in ids for j in ids)
    # Add up the tonne-kilometres (chips moved times distance) — reused for emissions later.
    tonne_km = sum(zval[i, j] * S[i] * dist[idx[i], idx[j]] for i in ids for j in ids)
    # Pack everything the next stage needs into the tidy solution object.
    return StageASolution(ids, S, dist, idx, xval, zval, cap, Cval, proc,
                          fixed_cost, transport_cost, tonne_km, status)


# =============================================================================
# 5. STAGE B  —  the money-and-carbon balance -> the break-even carbon credit
# =============================================================================
def stage_B(sol, nodes, p, fixed_cost=None, transport_cost=None,
            tonne_km=None, biochar_price=None) -> dict:
    """Take a layout (the optimal one, or a hand-made reference one) and work out
    the break-even carbon credit: the price per tonne of CO2 that would make the
    chain's income exactly match its costs.

    A HIGH credit means the chain needs a lot of support to survive; a NEGATIVE
    credit means it is already profitable with no credit at all.

    The optional arguments let us reuse this same function for the non-optimal
    reference layouts (we pass their costs in) and for sweeping the biochar price
    without re-solving Stage A (the price changes the income, not the map).
    """
    # The node names and their dry-biomass lookup, taken from the solution.
    ids = sol.ids
    S = sol.S
    # The purchase price of chips at each producer (euros per dry tonne).
    purchase_price = dict(zip(nodes["node"], nodes["prezzo_acq"]))
    # Use the given biochar price if provided, otherwise the base price in the parameters.
    pb = p["biochar_price"] if biochar_price is None else biochar_price
    # Use the given fixed cost if provided (reference layouts), otherwise the optimum's.
    cf = sol.fixed_cost if fixed_cost is None else fixed_cost
    # Same for the transport cost.
    ct = sol.transport_cost if transport_cost is None else transport_cost
    # Same for the tonne-kilometres (which drive the transport emissions).
    tk = sol.tonne_km if tonne_km is None else tonne_km

    # Total biomass processed across the whole chain (tonnes/year).
    bm = sum(sol.proc.values())
    # Biochar produced from it (yield times biomass).
    bc = p["biochar_yield"] * bm

    # --- MATERIAL COST (buying the chips, plus disposing of ash) ---
    # The chips are bought at the price of the PRODUCER that supplies them.
    biomass_cost = sum(sol.z[i, j] * S[i] * purchase_price[i] for i in ids for j in ids)
    # The cost of disposing of the solid residue (ash); the "waste price" is negative, so this is a cost.
    disposal_cost = bm * p["residue_yield"] * (-p["residue_price"])
    # Total material cost is the chips plus the disposal.
    material_cost = biomass_cost + disposal_cost

    # --- INCOME (selling biochar, by-products, and electricity) ---
    # Sellable electricity: the sellable share of syngas turned into MWh of power.
    energy_MWh = p["energy_yield"] * bm * p["syngas_lhv"] * p["elec_efficiency"] * p["sellable_fraction"]
    # Total income = biochar sales + by-product sales (zero by choice) + electricity sales.
    income = (p["biochar_yield"] * bm * pb
              + p["byproduct_yield"] * bm * p["byproduct_price"]
              + energy_MWh * p["energy_price"])

    # --- NET CO2 REMOVED (the denominator of the credit) ---
    # Carbon locked durably in the biochar, converted to its CO2 equivalent (the 44/12 ratio).
    e_storage = bc * p["carbon_fraction"] * p["stable_fraction"] * (44 / 12)
    # Emissions from moving the chips to the plants (tonne-kilometres times the haulage factor).
    e_biomass = tk * p["transport_emission"]
    # Emissions from making the biochar; kept at zero here but written out so the shape is visible.
    e_production = (bm * p["process_emission"]
                    + energy_MWh * p["grid_emission"]
                    + cf * p["capex_emission"])
    # Emissions from distributing and using the biochar; also zero here, shown for completeness.
    e_use = (bc * p["use_emission"]
             + bc * p["use_distance_km"] * p["transport_emission"])
    # Net removal = carbon stored minus all the emissions caused along the way.
    co2_net = e_storage - e_biomass - e_production - e_use

    # --- THE BREAK-EVEN CREDIT ITSELF ---
    # The full yearly cost is the fixed cost plus transport plus materials.
    full_cost = cf + ct + material_cost
    # The yearly shortfall left after income is counted.
    deficit = full_cost - income
    # The credit is that shortfall spread over each tonne of CO2 removed (guard against dividing by zero).
    credit = deficit / co2_net if co2_net else float("nan")
    # Return every ingredient in a labelled dictionary so the caller can print or plot any of it.
    return dict(biomass=bm, biochar=bc, biochar_t_day=bc / 365.0,
                co2_net=co2_net, e_storage=e_storage, e_biomass=e_biomass,
                e_production=e_production, e_use=e_use,
                fixed_cost=cf, transport_cost=ct,
                material_cost=material_cost, full_cost=full_cost,
                income=income, biochar_income=p["biochar_yield"] * bm * pb,
                energy_income=energy_MWh * p["energy_price"],
                energy_MWh=energy_MWh, deficit=deficit, breakeven_credit=credit,
                n_plants=int(sum(1 for j in ids if sol.x[j] > 0.5)))


# =============================================================================
# 6. REFERENCE LAYOUTS  —  deliberately non-optimal plans, for comparison only
#    These let us answer "does optimising actually help?" by comparing the
#    optimum against three naive plans.
# =============================================================================
def _config_costs(assign, nodes, p, scale, dist, idx, transport_cost_tkm):
    """Given a fixed plan `assign` (producer -> site), work out its fixed cost,
    transport cost and tonne-kilometres, and wrap it in a solution object so that
    Stage B can score it exactly like an optimised layout."""
    # The node names and their dry-biomass lookup.
    ids = nodes["node"].tolist()
    S = dict(zip(nodes["node"], nodes["S"]))
    # How much biomass lands at each site under this plan.
    proc = {j: sum(S[i] for i in ids if assign[i] == j) for j in ids}
    # Operating hours per year, to turn a yearly tonnage into a per-hour plant size.
    hours = p["hours_per_year"]
    # Prepare dictionaries for the per-site cost and size.
    C = {}
    cap = {}
    # Work out cost and size for every site in the plan.
    for j in ids:
        # A site with no biomass is closed: zero cost, zero size.
        if proc[j] <= 0:
            C[j] = 0.0
            cap[j] = 0.0
            continue
        # The size needed to process this site's biomass over the year.
        y_th = proc[j] / hours
        # The fixed cost of that size, read off the scale block's true cost curve.
        C[j] = scale.direct_yearly_cost(y_th, p)
        # Record the size.
        cap[j] = y_th
    # Total fixed cost of the plan.
    fixed_cost = sum(C.values())
    # Total transport cost: each producer's chips carried to its assigned site.
    transport_cost = sum(S[i] * dist[idx[i], idx[assign[i]]] * transport_cost_tkm for i in ids)
    # Total tonne-kilometres of the plan (for the emissions in Stage B).
    tonne_km = sum(S[i] * dist[idx[i], idx[assign[i]]] for i in ids)
    # Open/closed flags implied by the plan.
    x = {j: 1.0 if proc[j] > 0 else 0.0 for j in ids}
    # Routing fractions implied by the plan (1 where a producer is assigned, else 0).
    z = {(i, j): (1.0 if assign[i] == j else 0.0) for i in ids for j in ids}
    # Wrap it all in the same solution object the optimiser produces.
    return StageASolution(ids, S, dist, idx, x, z, cap, C, proc,
                          fixed_cost, transport_cost, tonne_km, "reference")


def config_centralized(nodes, p, scale, dist, idx, transport_cost_tkm):
    """Reference plan A: send EVERY producer to the single biggest-biomass site."""
    # The node names and biomass lookup.
    ids = nodes["node"].tolist()
    S = dict(zip(nodes["node"], nodes["S"]))
    # Pick the site with the most biomass as the single hub.
    hub = max(ids, key=lambda i: S[i])
    # Assign every producer to that hub.
    assign = {i: hub for i in ids}
    # Score the plan.
    return _config_costs(assign, nodes, p, scale, dist, idx, transport_cost_tkm)


def config_decentralized(nodes, p, scale, dist, idx, transport_cost_tkm):
    """Reference plan B: every producer processes its own chips on the spot (no transport)."""
    # The node names.
    ids = nodes["node"].tolist()
    # Assign every producer to itself.
    assign = {i: i for i in ids}
    # Score the plan.
    return _config_costs(assign, nodes, p, scale, dist, idx, transport_cost_tkm)


def config_random(nodes, p, scale, dist, idx, transport_cost_tkm,
                  n_samples=200, seed=20260826):
    """Reference plan C: many RANDOM admissible plans, to show the spread of bad luck.

    For each sample we open a random number of sites and send each producer to a
    random open site, then score it. We return the list of break-even credits.
    The random seed is fixed, so the result is the same every time you run it.
    """
    # A reproducible random-number generator seeded with a fixed number.
    rng = np.random.default_rng(seed)
    # The node names.
    ids = nodes["node"].tolist()
    # A place to collect the credit of each random plan.
    credits = []
    # Repeat the random experiment `n_samples` times.
    for _ in range(n_samples):
        # Choose how many sites to open this time (between 1 and all of them).
        k = int(rng.integers(1, len(ids) + 1))
        # Pick that many distinct sites at random to be the open ones.
        sites = list(rng.choice(ids, size=k, replace=False))
        # Assign each producer to one of the open sites at random.
        assign = {i: sites[int(rng.integers(0, k))] for i in ids}
        # Score this random plan through Stage A costs and Stage B.
        sol = _config_costs(assign, nodes, p, scale, dist, idx, transport_cost_tkm)
        kpi = stage_B(sol, nodes, p)
        # Keep its break-even credit.
        credits.append(kpi["breakeven_credit"])
    # Hand back all the credits as a number array (easy to average or plot).
    return np.array(credits)
